settings:
  title: 'Status Page'
  url: 'https://cf-workers-status-page-production.kolaente.workers.dev/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: 'Some checks failed'

monitors:
  - id: alpaca
    name: alpaca.kolaente.de
    url: 'https://alpaca.kolaente.de/health'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: cama
    name: cama.kolaente.de
    url: 'https://cama.kolaente.de/health'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: guanako
    name: guanako.kolaente.de
    url: 'https://guanako.kolaente.de/'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: kolaente.dev
    name: kolaente.dev
    url: 'https://kolaente.dev/'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: vikunjacloud
    name: 'Vikunja Cloud'
    url: 'https://my.vikunja.cloud/'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: vikunja-home
    name: 'Vikunja Homepage'
    url: 'https://vikunja.io/'
    method: GET
    expectStatus: 200
    followRedirect: false
  - id: mail
    name: 'Mailcow'
    url: 'https://mail.kolaente.de/'
    method: GET
    expectStatus: 200
    followRedirect: false

